// Stack Navigation
export const SPLASH_ROUTE = 'SPLASH_ROUTE';
export const SIGNIN_ROUTE = 'SIGNIN_ROUTE';
export const SIGNUP_ROUTE = 'SIGNUP_ROUTE';
export const MAINAPP_ROUTE = 'MAINAPP_ROUTE';
export const ADDPRODUCT_ROUTE = 'ADDPRODUCT_ROUTE';
export const PRODUCTDETAILS_ROUTE = 'PRODUCTDETAILS_ROUTE';

// Tab Navigation
export const HOME_ROUTE = 'HOME_ROUTE';
export const SEARCH_ROUTE = 'SEARCH_ROUTE';
export const MYPRODUCTS_ROUTE = 'MYPRODUCTS_ROUTE';
export const ACCOUNT_ROUTE = 'ACCOUNT_ROUTE';
